### ISSUE TITLE
Batch resize

### ISSUE THREAD

**Issue by alekksander** [T8RIN/ImageResizer#9]
Please allow user to mark and resize multiple files at once.

**Comment by T8RIN** [comment]
> Please allow user to mark and resize multiple files at once.

I will think about it👀

**Comment by yephny** [comment]
I think this feature is vital, especially since regular cropping is already supported by almost all gallery apps.

- There could be an option whether to keep or remove exif, like a checkbox, that would apply to all selected images.

- Cropping could work, have 2 ways (percentage and absolute) of entering dimensions. There are many cases where people have hundreds of images of the same size that all have the same kind of artifact in a specific spot.

**Comment by T8RIN** [comment]
thanks for the suggestions, it's really possible to do so, I'll add it as soon as I can 👀

**Comment by T8RIN** [comment]
Added this :)
